import { useState } from "react"

type RecordItem = { id: number; date: string; day: number; title: string; result: string; sets: string; duration: string; share: string; quick?: boolean }

const RECORDS: RecordItem[] = [
  { id: 1, date: "8月9日（土）", day: 9, title: "胸トレ", result: "80kg × 8回", sets: "3種目 · 9セット", duration: "52分", share: "自分のみ" },
  { id: 2, date: "8月9日（土）", day: 9, title: "腕立て伏せ", result: "30回", sets: "1セット", duration: "—", share: "チーム · 自宅トレ", quick: true },
  { id: 3, date: "8月7日（木）", day: 7, title: "胸トレ", result: "80kg × 8回", sets: "3種目 · 9セット", duration: "52分", share: "自分のみ" },
  { id: 4, date: "8月5日（火）", day: 5, title: "スクワット", result: "100kg × 5回", sets: "3セット", duration: "18分", share: "チーム · ジムA", quick: true },
  { id: 5, date: "8月1日（金）", day: 1, title: "下半身トレ", result: "100kg × 5回", sets: "4種目 · 12セット", duration: "64分", share: "自分のみ" },
]
const TRAINING_DAYS = new Set(RECORDS.map((record) => record.day))

export default function HistoryScreen({ onHome, onQuick }: { onHome: () => void; onQuick: () => void }) {
  const [selectedDay, setSelectedDay] = useState<number | null>(null)
  const [detail, setDetail] = useState<RecordItem | null>(null)
  const visible = selectedDay ? RECORDS.filter((record) => record.day === selectedDay) : RECORDS
  if (detail) return <HistoryDetail record={detail} onBack={() => setDetail(null)} onHome={onHome} onQuick={onQuick} />

  return <main style={pageStyle}><div style={contentStyle}>
    <div style={{ flex: 1, overflowY: "auto", paddingBottom: 92 }}>
      <header style={{ padding: "48px 24px 22px" }}><p style={eyebrowStyle}>PERSONAL HISTORY</p><h1 style={{ fontFamily: "Outfit", fontSize: 25, fontWeight: 700 }}>履歴</h1></header>
      <section style={{ margin: "0 24px", padding: "17px 16px 13px", backgroundColor: "#171717", border: "1px solid #2a2a2a", borderRadius: 16 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}><p style={{ fontFamily: "Outfit", fontSize: 15, fontWeight: 600 }}>2026年8月</p>{selectedDay && <button onClick={() => setSelectedDay(null)} style={{ background: "none", border: "none", color: "#c8ff00", fontFamily: "Inter", fontSize: 11, cursor: "pointer" }}>すべて表示</button>}</div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(7, 1fr)", marginBottom: 7 }}>{["日", "月", "火", "水", "木", "金", "土"].map((day, index) => <span key={day} style={{ textAlign: "center", color: index === 0 ? "#b35b5b" : index === 6 ? "#5b82b3" : "#666", fontSize: 10 }}>{day}</span>)}</div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: "3px 0" }}>{Array.from({ length: 35 }, (_, index) => { const date = index - 6; if (date < 1 || date > 31) return <div key={index} />; const trained = TRAINING_DAYS.has(date); const selected = selectedDay === date; return <button key={date} onClick={() => setSelectedDay(selected ? null : date)} style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 3, padding: "4px 0", border: "none", background: "transparent", color: selected ? "#0d0d0d" : trained ? "#ddd" : "#666", cursor: "pointer" }}><span style={{ width: 23, height: 23, display: "grid", placeItems: "center", borderRadius: "50%", backgroundColor: selected ? "#c8ff00" : "transparent", fontFamily: "Outfit", fontSize: 12, fontWeight: selected ? 700 : 400 }}>{date}</span><i style={{ width: 4, height: 4, borderRadius: "50%", backgroundColor: trained ? "#c8ff00" : "transparent" }} /></button> })}</div>
      </section>
      <section style={{ padding: "28px 24px 0" }}><p style={eyebrowStyle}>{selectedDay ? `8月${selectedDay}日の記録` : "すべての記録"}</p>{visible.length === 0 ? <p style={{ color: "#777", fontSize: 14, padding: "28px 0", textAlign: "center" }}>この日の記録はありません</p> : <div>{visible.map((record, index) => <div key={record.id}>{(index === 0 || visible[index - 1].date !== record.date) && <p style={{ fontFamily: "Outfit", color: "#aaa", fontSize: 14, fontWeight: 600, margin: index ? "24px 0 10px" : "0 0 10px" }}>{record.date}</p>}<button onClick={() => setDetail(record)} style={{ width: "100%", display: "flex", alignItems: "center", gap: 13, padding: "15px", backgroundColor: "#171717", border: "1px solid #2a2a2a", borderRadius: 14, color: "#f0f0f0", cursor: "pointer", textAlign: "left", marginBottom: 8 }}><div style={{ width: 35, height: 35, display: "grid", placeItems: "center", borderRadius: 9, backgroundColor: record.quick ? "#202020" : "#1b2500", color: record.quick ? "#aaa" : "#c8ff00", flexShrink: 0 }}>{record.quick ? "⚡" : "✓"}</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ display: "flex", gap: 7, alignItems: "center", marginBottom: 4 }}><span style={{ fontFamily: "Outfit", fontSize: 15, fontWeight: 600 }}>{record.title}</span>{record.quick && <span style={{ color: "#888", fontSize: 10, border: "1px solid #333", borderRadius: 4, padding: "2px 4px" }}>クイック</span>}</div><p style={{ color: "#ccc", fontFamily: "Outfit", fontSize: 13 }}>{record.result}<span style={{ color: "#666", fontFamily: "Inter", fontSize: 11 }}>　{record.sets} · {record.duration}</span></p><p style={{ color: "#777", fontSize: 11, marginTop: 5 }}>{record.share}</p></div><span style={{ color: "#555" }}>›</span></button></div>)}</div>}</section>
    </div>
    <HistoryNav onHome={onHome} onQuick={onQuick} />
  </div></main>
}

function HistoryDetail({ record, onBack, onHome, onQuick }: { record: RecordItem; onBack: () => void; onHome: () => void; onQuick: () => void }) { return <main style={pageStyle}><div style={contentStyle}><header style={{ display: "flex", alignItems: "center", gap: 15, padding: "28px 24px 20px", borderBottom: "1px solid #1e1e1e" }}><button onClick={onBack} style={{ width: 38, height: 38, borderRadius: 10, background: "#202020", border: "1px solid #2a2a2a", color: "#ddd", cursor: "pointer", fontSize: 22 }}>‹</button><div><p style={eyebrowStyle}>RECORD DETAIL</p><h1 style={{ fontFamily: "Outfit", fontSize: 20, fontWeight: 700 }}>{record.title}</h1></div></header><div style={{ padding: "24px", paddingBottom: 100 }}><p style={{ color: "#888", fontSize: 13, marginBottom: 18 }}>{record.date}　{record.share}</p><section style={cardStyle}><p style={{ color: "#777", fontSize: 11, marginBottom: 8 }}>実績</p><p style={{ fontFamily: "Outfit", fontSize: 26, fontWeight: 700 }}>{record.result}</p><p style={{ color: "#aaa", fontSize: 13, marginTop: 12 }}>{record.sets}　·　実施時間 {record.duration}</p></section>{!record.quick && <section style={{ ...cardStyle, marginTop: 14 }}><p style={{ fontFamily: "Outfit", fontWeight: 600, marginBottom: 12 }}>実施種目</p><p style={{ color: "#bbb", fontSize: 14 }}>ベンチプレス　80kg × 8回</p><p style={{ color: "#bbb", fontSize: 14, marginTop: 10 }}>インクラインDB　30kg × 10回</p></section>}</div><HistoryNav onHome={onHome} onQuick={onQuick} /></div></main> }

function HistoryNav({ onHome, onQuick }: { onHome: () => void; onQuick: () => void }) { return <nav style={navStyle}><button onClick={onHome} style={navButtonStyle}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9.5L12 3l9 6.5V20a1 1 0 01-1 1H4a1 1 0 01-1-1V9.5z" /><path d="M9 21V12h6v9" /></svg><span style={navLabelStyle}>ホーム</span></button><button onClick={onQuick} style={{ ...navButtonStyle, padding: "0 0 2px" }}><div style={{ width: 48, height: 48, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#222", border: "1px solid #333", marginTop: -10, fontSize: 22, fontWeight: 400 }}>＋</div><span style={navLabelStyle}>記録</span></button><button style={{ ...navButtonStyle, color: "#c8ff00" }}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 3" /></svg><span style={{ ...navLabelStyle, fontWeight: 600 }}>履歴</span></button></nav> }

const pageStyle = { minHeight: "100vh", display: "flex", justifyContent: "center", backgroundColor: "#000" } as const
const contentStyle = { width: "100%", maxWidth: 430, minHeight: "100vh", position: "relative", display: "flex", flexDirection: "column", backgroundColor: "#0d0d0d" } as const
const eyebrowStyle = { color: "#666", fontFamily: "Inter", fontSize: 11, fontWeight: 500, letterSpacing: "0.1em", marginBottom: 5 } as const
const cardStyle = { backgroundColor: "#171717", border: "1px solid #2a2a2a", borderRadius: 16, padding: "18px" } as const
const navStyle = { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 430, display: "flex", alignItems: "flex-end", padding: "8px 0 20px", backgroundColor: "#0d0d0d", borderTop: "1px solid #1e1e1e", zIndex: 10 } as const
const navButtonStyle = { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 4, border: "none", background: "none", color: "#505050", cursor: "pointer", padding: "6px 0" } as const
const navLabelStyle = { fontFamily: "Inter", fontSize: 10, letterSpacing: "0.04em" } as const
