import { useState } from "react"

const REGISTERED_EXERCISES = ["ベンチプレス", "インクラインDB", "ケーブルフライ", "スクワット", "デッドリフト", "懸垂", "ショルダープレス"]
type MenuExercise = { id: number; name: string; sets: number }

export default function MenuEditorScreen({ onBack }: { onBack: () => void }) {
  const [menuName, setMenuName] = useState("胸トレ")
  const [items, setItems] = useState<MenuExercise[]>([{ id: 1, name: "ベンチプレス", sets: 3 }, { id: 2, name: "インクラインDB", sets: 3 }, { id: 3, name: "ケーブルフライ", sets: 3 }])
  const [pickerOpen, setPickerOpen] = useState(false)
  const [newExerciseOpen, setNewExerciseOpen] = useState(false)
  const [newExercise, setNewExercise] = useState("")
  const [confirmDelete, setConfirmDelete] = useState(false)
  const [saved, setSaved] = useState(false)
  const [dragId, setDragId] = useState<number | null>(null)
  const addExercise = (name: string) => { if (!items.some((item) => item.name === name)) setItems((value) => [...value, { id: Date.now(), name, sets: 3 }]); setPickerOpen(false) }
  const move = (from: number, to: number) => setItems((value) => { const next = [...value]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next })
  if (saved) return <main style={pageStyle}><div style={{ ...contentStyle, justifyContent: "center", alignItems: "center", padding: 24, textAlign: "center" }}><div style={{ width: 60, height: 60, display: "grid", placeItems: "center", borderRadius: "50%", background: "#1b2500", border: "1px solid #c8ff00", color: "#c8ff00", fontSize: 28 }}>✓</div><p style={{ fontFamily: "Outfit", fontSize: 21, fontWeight: 700, marginTop: 18 }}>メニューを保存しました</p><button onClick={onBack} style={{ ...saveStyle, marginTop: 28 }}>戻る</button></div></main>
  return <main style={pageStyle}><div style={contentStyle}>
    <header style={{ display: "flex", alignItems: "center", gap: 14, padding: "24px 20px 18px", borderBottom: "1px solid #1e1e1e" }}><button onClick={onBack} style={backStyle}>‹</button><div style={{ flex: 1 }}><p style={eyebrowStyle}>WORKOUT MENU</p><h1 style={{ fontFamily: "Outfit", fontSize: 21, fontWeight: 700 }}>メニューを編集</h1></div><button onClick={() => { setMenuName(""); setItems([]); setPickerOpen(false); setNewExerciseOpen(false) }} style={{ padding: "8px 10px", border: "1px solid #333", borderRadius: 8, background: "transparent", color: "#c8ff00", fontFamily: "Inter", fontSize: 12, cursor: "pointer" }}>新規作成</button></header>
    <div style={{ flex: 1, overflowY: "auto", padding: "22px 24px 126px" }}>
      <p style={labelStyle}>メニュー名</p><input value={menuName} onChange={(event) => setMenuName(event.target.value)} placeholder="例：胸トレ" style={inputStyle} />
      <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", marginTop: 29, marginBottom: 10 }}><p style={labelStyle}>種目</p><span style={{ color: "#666", fontSize: 11 }}>ドラッグして並べ替え</span></div>
      {items.map((item, index) => <div key={item.id} draggable onDragStart={() => setDragId(item.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => { const from = items.findIndex((value) => value.id === dragId); if (from >= 0 && from !== index) move(from, index); setDragId(null) }} style={{ display: "flex", alignItems: "center", gap: 10, padding: "13px 12px", marginBottom: 8, background: "#171717", border: "1px solid #2a2a2a", borderRadius: 12 }}><span style={{ color: "#555", cursor: "grab", letterSpacing: "-2px" }}>⠿</span><span style={{ flex: 1, fontFamily: "Outfit", fontSize: 15, fontWeight: 600 }}>{item.name}</span><div style={{ display: "flex", alignItems: "center", gap: 6 }}><button onClick={() => setItems((value) => value.map((entry) => entry.id === item.id ? { ...entry, sets: Math.max(1, entry.sets - 1) } : entry))} style={stepStyle}>−</button><span style={{ width: 42, textAlign: "center", fontFamily: "Outfit", fontSize: 14 }}>{item.sets}セット</span><button onClick={() => setItems((value) => value.map((entry) => entry.id === item.id ? { ...entry, sets: entry.sets + 1 } : entry))} style={stepStyle}>＋</button></div><button onClick={() => setItems((value) => value.filter((entry) => entry.id !== item.id))} aria-label={`${item.name}を削除`} style={{ border: "none", background: "none", color: "#8a5555", cursor: "pointer", fontSize: 18 }}>×</button></div>)}
      <button onClick={() => setPickerOpen((value) => !value)} style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, padding: "15px", background: "transparent", border: "1px dashed #3a3a3a", borderRadius: 12, color: "#aaa", fontFamily: "Inter", fontSize: 13, cursor: "pointer" }}>＋ 種目を追加</button>
      {pickerOpen && <section style={{ ...cardStyle, marginTop: 10 }}><p style={{ ...labelStyle, marginBottom: 10 }}>登録済みの種目</p>{REGISTERED_EXERCISES.filter((name) => !items.some((item) => item.name === name)).map((name) => <button key={name} onClick={() => addExercise(name)} style={pickerItemStyle}>{name}<span>＋</span></button>)}<button onClick={() => { setPickerOpen(false); setNewExerciseOpen(true) }} style={{ ...pickerItemStyle, color: "#c8ff00", borderBottom: "none" }}>新規種目を作成<span>＋</span></button></section>}
      {newExerciseOpen && <section style={{ ...cardStyle, marginTop: 10 }}><p style={{ ...labelStyle, marginBottom: 10 }}>新規種目名</p><div style={{ display: "flex", gap: 8 }}><input autoFocus value={newExercise} onChange={(event) => setNewExercise(event.target.value)} placeholder="種目名を入力" style={{ ...inputStyle, minWidth: 0 }} /><button onClick={() => { if (newExercise.trim()) { addExercise(newExercise.trim()); setNewExercise(""); setNewExerciseOpen(false) } }} style={{ padding: "0 14px", border: "none", borderRadius: 9, background: "#c8ff00", color: "#0d0d0d", fontFamily: "Outfit", fontWeight: 700, cursor: "pointer" }}>追加</button></div></section>}
      <button onClick={() => setConfirmDelete(true)} style={{ width: "100%", marginTop: 28, padding: "14px", border: "1px solid #4a2929", borderRadius: 12, background: "transparent", color: "#df7777", fontFamily: "Inter", fontSize: 13, cursor: "pointer" }}>このメニューを削除</button>
    </div>
    <footer style={footerStyle}><button onClick={onBack} style={{ ...saveStyle, flex: 1, background: "#202020", border: "1px solid #333", color: "#ddd" }}>キャンセル</button><button disabled={!menuName.trim() || items.length === 0} onClick={() => setSaved(true)} style={{ ...saveStyle, flex: 1.15, opacity: menuName.trim() && items.length ? 1 : 0.35 }}>メニューを保存</button></footer>
    {confirmDelete && <div style={overlayStyle}><section style={dialogStyle}><p style={{ fontFamily: "Outfit", fontSize: 18, fontWeight: 700, marginBottom: 9 }}>メニューを削除しますか？</p><p style={{ color: "#888", fontSize: 13, lineHeight: 1.5, marginBottom: 22 }}>「{menuName || "このメニュー"}」を削除します。元に戻せません。</p><div style={{ display: "flex", gap: 9 }}><button onClick={() => setConfirmDelete(false)} style={{ ...dialogButtonStyle, background: "#202020", color: "#ddd" }}>キャンセル</button><button onClick={onBack} style={{ ...dialogButtonStyle, background: "#d94b4b", color: "#fff" }}>削除する</button></div></section></div>}
  </div></main>
}
const pageStyle = { minHeight: "100vh", display: "flex", justifyContent: "center", background: "#000" } as const
const contentStyle = { width: "100%", maxWidth: 430, minHeight: "100vh", display: "flex", flexDirection: "column", position: "relative", background: "#0d0d0d" } as const
const eyebrowStyle = { color: "#666", fontFamily: "Inter", fontSize: 11, letterSpacing: "0.1em", marginBottom: 4 } as const
const labelStyle = { color: "#aaa", fontFamily: "Outfit", fontSize: 13, fontWeight: 600 } as const
const inputStyle = { width: "100%", height: 52, padding: "0 14px", border: "1px solid #2a2a2a", borderRadius: 11, background: "#171717", color: "#f0f0f0", outline: "none", fontFamily: "Inter", fontSize: 14 } as const
const backStyle = { width: 38, height: 38, border: "1px solid #2a2a2a", borderRadius: 10, background: "#202020", color: "#ddd", cursor: "pointer", fontSize: 22 } as const
const stepStyle = { width: 26, height: 26, border: "1px solid #333", borderRadius: 7, background: "#202020", color: "#bbb", cursor: "pointer", fontSize: 16 } as const
const cardStyle = { padding: "14px", border: "1px solid #2a2a2a", borderRadius: 12, background: "#171717" } as const
const pickerItemStyle = { width: "100%", display: "flex", justifyContent: "space-between", padding: "12px 2px", border: "none", borderBottom: "1px solid #282828", background: "transparent", color: "#ccc", textAlign: "left", fontFamily: "Inter", fontSize: 13, cursor: "pointer" } as const
const footerStyle = { position: "absolute", bottom: 0, width: "100%", display: "flex", gap: 10, padding: "14px 24px 28px", borderTop: "1px solid #1e1e1e", background: "#0d0d0d" } as const
const saveStyle = { height: 52, border: "none", borderRadius: 12, background: "#c8ff00", color: "#0d0d0d", fontFamily: "Outfit", fontSize: 14, fontWeight: 700, cursor: "pointer" } as const
const overlayStyle = { position: "fixed", inset: 0, zIndex: 30, display: "flex", alignItems: "center", justifyContent: "center", padding: 24, background: "rgba(0,0,0,0.7)" } as const
const dialogStyle = { width: "100%", maxWidth: 360, padding: 22, border: "1px solid #333", borderRadius: 16, background: "#171717" } as const
const dialogButtonStyle = { flex: 1, height: 46, border: "none", borderRadius: 10, fontFamily: "Inter", fontSize: 13, fontWeight: 600, cursor: "pointer" } as const
