import { useState } from "react"

type Workspace = { id: number; name: string; type: "個人" | "チーム" }

export default function SettingsScreen({ onHome, onQuick, onHistory, onMenuEditor, onExerciseManager, onCreateTeam, onWorkspaceManager, tendency, onTendency, workspaces, currentWorkspaceId, onSelectWorkspace, restEnabled, onRestEnabled, restSeconds, onRestSeconds }: { onHome: () => void; onQuick: () => void; onHistory: () => void; onMenuEditor: () => void; onExerciseManager: () => void; onCreateTeam: () => void; onWorkspaceManager: () => void; tendency: string; onTendency: (value: string) => void; workspaces: Workspace[]; currentWorkspaceId: number; onSelectWorkspace: (id: number) => void; restEnabled: boolean; onRestEnabled: (value: boolean) => void; restSeconds: number; onRestSeconds: (value: number) => void }) {
  const [workspaceOpen, setWorkspaceOpen] = useState(false)
  const currentWorkspace = workspaces.find((workspace) => workspace.id === currentWorkspaceId) ?? workspaces[0]

  return <main style={pageStyle}><div style={contentStyle}>
    <div style={{ flex: 1, overflowY: "auto", padding: "48px 24px 108px" }}>
      <p style={eyebrowStyle}>SETTINGS</p><h1 style={{ fontFamily: "Outfit", fontSize: 25, fontWeight: 700, marginBottom: 28 }}>設定</h1>

      <Section title="プロフィール"><div style={profileStyle}><div style={avatarStyle}>田</div><div><p style={{ fontFamily: "Outfit", fontSize: 16, fontWeight: 700, marginBottom: 4 }}>田中 太郎</p><p style={{ color: "#777", fontSize: 12 }}>tanaka@example.com</p></div></div></Section>

      <Section title="トレーニング"><div style={rowStyle}><div><p style={rowTitleStyle}>休憩タイマー</p><p style={detailStyle}>セット完了後に自動で開始</p></div><button onClick={() => onRestEnabled(!restEnabled)} aria-label={`休憩タイマー ${restEnabled ? "ON" : "OFF"}`} style={{ ...switchStyle, background: restEnabled ? "#c8ff00" : "#333" }}><i style={{ ...knobStyle, marginLeft: restEnabled ? 19 : 0, background: restEnabled ? "#0d0d0d" : "#aaa" }} /></button></div><div style={{ ...rowStyle, borderTop: "1px solid #282828" }}><div><p style={rowTitleStyle}>休憩時間</p><p style={detailStyle}>初期値</p></div><div style={{ display: "flex", alignItems: "center", gap: 8, opacity: restEnabled ? 1 : .4 }}><button disabled={!restEnabled} onClick={() => onRestSeconds(Math.max(10, restSeconds - 10))} style={restStepStyle}>−</button><span style={{ width: 43, textAlign: "center", fontFamily: "Outfit", fontSize: 16, fontWeight: 700 }}>{restSeconds}秒</span><button disabled={!restEnabled} onClick={() => onRestSeconds(restSeconds + 10)} style={restStepStyle}>＋</button></div></div><div style={{ padding: "16px" }}><p style={rowTitleStyle}>トレーニング傾向</p><p style={{ ...detailStyle, marginTop: 4, marginBottom: 13 }}>よく行うトレーニング</p><div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 7 }}>{["自重中心", "器具中心", "両方"].map((item) => <button key={item} onClick={() => onTendency(item)} style={{ ...tendencyStyle, borderColor: tendency === item ? "#c8ff00" : "#333", background: tendency === item ? "#1b2500" : "#202020", color: tendency === item ? "#c8ff00" : "#999" }}>{item}</button>)}</div></div></Section>

      <Section title="ワークスペース"><div style={{ padding: "16px", borderBottom: "1px solid #282828" }}><p style={rowTitleStyle}>現在のワークスペース</p><button onClick={() => setWorkspaceOpen((value) => !value)} style={workspaceButtonStyle}><span><strong style={{ fontFamily: "Outfit", fontSize: 16 }}>{currentWorkspace.name}</strong><small style={badgeStyle}>{currentWorkspace.type}</small></span><span style={{ color: "#777", fontSize: 18 }}>{workspaceOpen ? "⌃" : "⌄"}</span></button></div>{workspaceOpen && <div>{workspaces.map((workspace) => <button key={workspace.id} onClick={() => { onSelectWorkspace(workspace.id); setWorkspaceOpen(false) }} style={{ ...workspaceRowStyle, background: workspace.id === currentWorkspaceId ? "#202020" : "transparent", color: workspace.id === currentWorkspaceId ? "#c8ff00" : "#ddd" }}><span>{workspace.name}<small style={badgeStyle}>{workspace.type}</small></span>{workspace.id === currentWorkspaceId && <span>✓</span>}</button>)}</div>}<button onClick={onCreateTeam} style={teamLinkStyle}><span style={teamIconStyle}>＋</span><span style={teamTextStyle}><strong>チームワークスペースを作成</strong><small>仲間と記録を共有できます</small></span><span style={teamArrowStyle}>›</span></button></Section>

      <Section title="管理"><Row title="ワークスペースを管理" detail="名前変更・メンバー確認" onClick={onWorkspaceManager} /><Row title="トレーニングメニューを管理" detail="胸トレ、脚トレなど" onClick={onMenuEditor} /><Row title="種目を管理" detail="登録済み種目を編集" onClick={onExerciseManager} last /></Section>
    </div>
    <SettingsNav onHome={onHome} onQuick={onQuick} onHistory={onHistory} />
  </div></main>
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section style={{ marginBottom: 27 }}><p style={labelStyle}>{title}</p><div style={sectionStyle}>{children}</div></section> }
function Row({ title, detail, onClick, last }: { title: string; detail: string; onClick: () => void; last?: boolean }) { return <button onClick={onClick} style={{ ...rowStyle, width: "100%", textAlign: "left", cursor: "pointer", borderTop: last ? "none" : "none", borderBottom: last ? "none" : "1px solid #282828" }}><div style={{ flex: 1 }}><p style={rowTitleStyle}>{title}</p><p style={detailStyle}>{detail}</p></div><span style={{ color: "#666", fontSize: 19 }}>›</span></button> }
function SettingsNav({ onHome, onQuick, onHistory }: { onHome: () => void; onQuick: () => void; onHistory: () => void }) { return <nav style={navStyle}><NavButton onClick={onHome} icon="home" label="ホーム" /><NavButton onClick={onQuick} icon="plus" label="記録" /><NavButton onClick={onHistory} icon="history" label="履歴" /><NavButton icon="settings" label="設定" active /></nav> }
function NavButton({ onClick, icon, label, active }: { onClick?: () => void; icon: string; label: string; active?: boolean }) { const color = active ? "#c8ff00" : "#505050"; return <button onClick={onClick} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 4, padding: icon === "plus" ? "0 0 2px" : "6px 0", background: "none", border: "none", color, cursor: "pointer" }}>{icon === "plus" ? <div style={{ width: 48, height: 48, display: "grid", placeItems: "center", borderRadius: 14, background: "#222", border: "1px solid #333", marginTop: -10, color: "#f0f0f0", fontSize: 22 }}>＋</div> : <NavIcon icon={icon} />}<span style={{ fontFamily: "Inter", fontSize: 10, fontWeight: active ? 600 : 400, letterSpacing: "0.04em" }}>{label}</span></button> }
function NavIcon({ icon }: { icon: string }) { return icon === "settings" ? <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="3" /><path d="M19.4 15a1.7 1.7 0 00.3 1.9l.1.1-2.2 2.2-.1-.1a1.7 1.7 0 00-1.9-.3 1.7 1.7 0 00-1 1.5v.2h-3.2v-.2a1.7 1.7 0 00-1-1.5 1.7 1.7 0 00-1.9.3l-.1.1-2.2-2.2.1-.1a1.7 1.7 0 00.3-1.9 1.7 1.7 0 00-1.5-1H5v-3.2h.2a1.7 1.7 0 001.5-1 1.7 1.7 0 00-.3-1.9l-.1-.1 2.2-2.2.1.1a1.7 1.7 0 001.9.3 1.7 1.7 0 001-1.5V4h3.2v.2a1.7 1.7 0 001 1.5 1.7 1.7 0 001.9-.3l.1-.1 2.2 2.2-.1.1a1.7 1.7 0 00-.3 1.9 1.7 1.7 0 001.5 1h.2V14h-.2a1.7 1.7 0 00-1.5 1z" /></svg> : icon === "history" ? <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 3" /></svg> : <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 9.5L12 3l9 6.5V20a1 1 0 01-1 1H4a1 1 0 01-1-1V9.5z" /><path d="M9 21V12h6v9" /></svg> }

const pageStyle = { minHeight: "100vh", display: "flex", justifyContent: "center", background: "#000" } as const
const contentStyle = { width: "100%", maxWidth: 430, minHeight: "100vh", display: "flex", flexDirection: "column", background: "#0d0d0d" } as const
const eyebrowStyle = { color: "#666", fontFamily: "Inter", fontSize: 11, letterSpacing: "0.1em", marginBottom: 5 } as const
const labelStyle = { color: "#777", fontSize: 11, fontWeight: 500, letterSpacing: "0.1em", marginBottom: 10 } as const
const sectionStyle = { border: "1px solid #2a2a2a", borderRadius: 14, background: "#171717", overflow: "hidden" } as const
const profileStyle = { display: "flex", alignItems: "center", gap: 13, padding: "16px" } as const
const avatarStyle = { width: 40, height: 40, display: "grid", placeItems: "center", borderRadius: "50%", background: "#202020", border: "1px solid #333", color: "#aaa", fontFamily: "Outfit", fontWeight: 700 } as const
const rowStyle = { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 14, padding: "16px", background: "transparent", border: "none", color: "#f0f0f0" } as const
const rowTitleStyle = { fontFamily: "Outfit", fontSize: 15, fontWeight: 600 } as const
const detailStyle = { color: "#777", fontSize: 12, marginTop: 4 } as const
const switchStyle = { width: 46, height: 27, padding: 3, border: "none", borderRadius: 20, cursor: "pointer" } as const
const knobStyle = { display: "block", width: 21, height: 21, borderRadius: "50%", transition: "margin-left 0.15s" } as const
const tendencyStyle = { padding: "10px 4px", border: "1px solid", borderRadius: 9, fontFamily: "Inter", fontSize: 11, cursor: "pointer" } as const
const restStepStyle = { width: 28, height: 28, border: "1px solid #333", borderRadius: 8, background: "#202020", color: "#bbb", cursor: "pointer", fontSize: 16 } as const
const workspaceButtonStyle = { display: "flex", width: "100%", alignItems: "center", justifyContent: "space-between", padding: "12px 0 0", border: "none", background: "transparent", color: "#f0f0f0", textAlign: "left", cursor: "pointer" } as const
const badgeStyle = { display: "inline-block", marginLeft: 8, padding: "2px 6px", borderRadius: 4, background: "#282828", color: "#999", fontSize: 10, fontFamily: "Inter", fontWeight: 400, verticalAlign: "middle" } as const
const workspaceRowStyle = { display: "flex", width: "100%", alignItems: "center", justifyContent: "space-between", padding: "13px 16px", border: "none", borderBottom: "1px solid #282828", fontFamily: "Inter", fontSize: 13, textAlign: "left", cursor: "pointer" } as const
const teamLinkStyle = { display: "flex", width: "100%", alignItems: "center", gap: 12, padding: "16px", border: "none", background: "transparent", color: "#c8ff00", textAlign: "left", cursor: "pointer", fontFamily: "Inter" } as const
const teamIconStyle = { width: 28, height: 28, display: "grid", placeItems: "center", flexShrink: 0, border: "1px solid #586f00", borderRadius: 8, background: "#1b2500", fontSize: 18 } as const
const teamTextStyle = { flex: 1, display: "flex", flexDirection: "column", gap: 3, fontSize: 13 } as const
const teamArrowStyle = { color: "#777", fontSize: 20 } as const
const navStyle = { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 430, display: "flex", alignItems: "flex-end", padding: "8px 0 20px", background: "#0d0d0d", borderTop: "1px solid #1e1e1e", zIndex: 10 } as const
