import { useState } from "react"

export default function SettingsScreen({ onHome, onQuick, onHistory, onMenuEditor }: { onHome: () => void; onQuick: () => void; onHistory: () => void; onMenuEditor: () => void }) {
  const [restEnabled, setRestEnabled] = useState(true)
  const [restSeconds, setRestSeconds] = useState(90)
  const [tendency, setTendency] = useState("両方")
  return <main style={pageStyle}><div style={contentStyle}><div style={{ flex: 1, overflowY: "auto", padding: "48px 24px 108px" }}><p style={eyebrowStyle}>SETTINGS</p><h1 style={{ fontFamily: "Outfit", fontSize: 25, fontWeight: 700, marginBottom: 26 }}>設定</h1><p style={labelStyle}>アカウント</p><section style={cardStyle}><Row title="プロフィール" detail="田中 太郎" arrow /></section><p style={{ ...labelStyle, marginTop: 26 }}>トレーニング</p><section style={{ ...cardStyle, padding: 0, overflow: "hidden" }}><Row title="トレーニングメニューを管理" detail="胸トレ、脚トレなど" arrow onClick={onMenuEditor} /><Row title="種目を管理" detail="準備中" arrow /></section><p style={{ ...labelStyle, marginTop: 26 }}>休憩タイマー</p><section style={cardStyle}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}><div><p style={{ fontFamily: "Outfit", fontSize: 15, fontWeight: 600, marginBottom: 4 }}>休憩タイマー</p><p style={{ color: "#777", fontSize: 12 }}>セット完了後に自動で開始</p></div><button onClick={() => setRestEnabled((value) => !value)} style={{ width: 46, height: 27, padding: 3, border: "none", borderRadius: 20, background: restEnabled ? "#c8ff00" : "#333", cursor: "pointer" }}><i style={{ display: "block", width: 21, height: 21, marginLeft: restEnabled ? 19 : 0, borderRadius: "50%", background: restEnabled ? "#0d0d0d" : "#aaa", transition: "margin-left 0.15s" }} /></button></div>{restEnabled && <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 18, paddingTop: 16, borderTop: "1px solid #292929" }}><span style={{ color: "#aaa", fontSize: 13 }}>初期値</span><div style={{ display: "flex", alignItems: "center", gap: 8 }}><button onClick={() => setRestSeconds((value) => Math.max(10, value - 10))} style={stepStyle}>−</button><span style={{ width: 48, textAlign: "center", fontFamily: "Outfit", fontWeight: 700 }}>{restSeconds}秒</span><button onClick={() => setRestSeconds((value) => value + 10)} style={stepStyle}>＋</button></div></div>}</section><p style={{ ...labelStyle, marginTop: 26 }}>ワークスペース</p><section style={cardStyle}><Row title="ワークスペース管理" detail="自宅トレ、ジムA" arrow /></section><p style={{ ...labelStyle, marginTop: 26 }}>トレーニング傾向</p><section style={cardStyle}><p style={{ color: "#777", fontSize: 12, marginBottom: 14 }}>よく行うトレーニングを教えてください</p><div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 7 }}>{["自重中心", "器具中心", "両方"].map((item) => <button key={item} onClick={() => setTendency(item)} style={{ padding: "10px 4px", border: `1px solid ${tendency === item ? "#c8ff00" : "#333"}`, borderRadius: 9, background: tendency === item ? "#1b2500" : "#202020", color: tendency === item ? "#c8ff00" : "#999", fontFamily: "Inter", fontSize: 11, cursor: "pointer" }}>{item}</button>)}</div></section></div><SettingsNav onHome={onHome} onQuick={onQuick} onHistory={onHistory} /></div></main>
}

function Row({ title, detail, arrow, onClick }: { title: string; detail: string; arrow?: boolean; onClick?: () => void }) { return <button onClick={onClick} style={{ display: "flex", alignItems: "center", width: "100%", padding: "16px", background: "transparent", border: "none", borderBottom: "1px solid #282828", color: "#f0f0f0", textAlign: "left", cursor: onClick ? "pointer" : "default" }}><div style={{ flex: 1 }}><p style={{ fontFamily: "Outfit", fontSize: 15, fontWeight: 600, marginBottom: 4 }}>{title}</p><p style={{ color: "#777", fontSize: 12 }}>{detail}</p></div>{arrow && <span style={{ color: "#666", fontSize: 19 }}>›</span>}</button> }
function SettingsNav({ onHome, onQuick, onHistory }: { onHome: () => void; onQuick: () => void; onHistory: () => void }) { return <nav style={navStyle}><NavButton onClick={onHome} icon="home" label="ホーム" /><NavButton onClick={onQuick} icon="plus" label="記録" /><NavButton onClick={onHistory} icon="history" label="履歴" /><NavButton icon="settings" label="設定" active /></nav> }
function NavButton({ onClick, icon, label, active }: { onClick?: () => void; icon: string; label: string; active?: boolean }) { const color = active ? "#c8ff00" : "#505050"; return <button onClick={onClick} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 4, padding: icon === "plus" ? "0 0 2px" : "6px 0", background: "none", border: "none", color, cursor: "pointer" }}>{icon === "plus" ? <div style={{ width: 48, height: 48, display: "grid", placeItems: "center", borderRadius: 14, background: "#222", border: "1px solid #333", marginTop: -10, color: "#f0f0f0", fontSize: 22 }}>＋</div> : <NavIcon icon={icon} />}<span style={{ fontFamily: "Inter", fontSize: 10, fontWeight: active ? 600 : 400, letterSpacing: "0.04em" }}>{label}</span></button> }
function NavIcon({ icon }: { icon: string }) { return icon === "settings" ? <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="3" /><path d="M19.4 15a1.7 1.7 0 00.3 1.9l.1.1-2.2 2.2-.1-.1a1.7 1.7 0 00-1.9-.3 1.7 1.7 0 00-1 1.5v.2h-3.2v-.2a1.7 1.7 0 00-1-1.5 1.7 1.7 0 00-1.9.3l-.1.1-2.2-2.2.1-.1a1.7 1.7 0 00.3-1.9 1.7 1.7 0 00-1.5-1H5v-3.2h.2a1.7 1.7 0 001.5-1 1.7 1.7 0 00-.3-1.9l-.1-.1 2.2-2.2.1.1a1.7 1.7 0 001.9.3 1.7 1.7 0 001-1.5V4h3.2v.2a1.7 1.7 0 001 1.5 1.7 1.7 0 001.9-.3l.1-.1 2.2 2.2-.1.1a1.7 1.7 0 00-.3 1.9 1.7 1.7 0 001.5 1h.2V14h-.2a1.7 1.7 0 00-1.5 1z" /></svg> : icon === "history" ? <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 3" /></svg> : <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 9.5L12 3l9 6.5V20a1 1 0 01-1 1H4a1 1 0 01-1-1V9.5z" /><path d="M9 21V12h6v9" /></svg> }
const pageStyle = { minHeight: "100vh", display: "flex", justifyContent: "center", background: "#000" } as const
const contentStyle = { width: "100%", maxWidth: 430, minHeight: "100vh", display: "flex", flexDirection: "column", background: "#0d0d0d" } as const
const eyebrowStyle = { color: "#666", fontFamily: "Inter", fontSize: 11, letterSpacing: "0.1em", marginBottom: 5 } as const
const labelStyle = { color: "#777", fontSize: 11, fontWeight: 500, letterSpacing: "0.1em" } as const
const cardStyle = { border: "1px solid #2a2a2a", borderRadius: 15, background: "#171717", padding: "16px" } as const
const stepStyle = { width: 28, height: 28, border: "1px solid #333", borderRadius: 8, background: "#202020", color: "#bbb", cursor: "pointer", fontSize: 16 } as const
const navStyle = { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 430, display: "flex", alignItems: "flex-end", padding: "8px 0 20px", background: "#0d0d0d", borderTop: "1px solid #1e1e1e", zIndex: 10 } as const
