import { useState } from "react"
import type { TeamMember, TeamRole, SharedRecord } from "./TeamMemberScreen"
import type { GrowthPhoto } from "./GrowthScreen"

export type TeamInvitation = { id: string; workspaceId: string; email: string; createdAt: string; expiresAt: string; acceptedAt: string | null; revokedAt: string | null }

export type TeamManageCallbacks = { onRemoveMember?: (id: string) => Promise<boolean> | boolean | void; onTransferOwnership?: (id: string) => Promise<boolean> | boolean; onUnshareRecord?: (id: string) => Promise<boolean> | boolean | void; onUnsharePhoto?: (id: string) => Promise<boolean> | boolean | void; onDeletePhoto?: (id: string) => Promise<boolean> | boolean | void }
export default function TeamManageScreen({ teamName, members, records, photos, photosLoading, invitations, currentUserId, currentRole, saving, error, invitationSaving, invitationError, onBack, onRoleChange, onCreateInvitation, onRevokeInvitation, onRemoveRecord, onRemoveMember, onTransferOwnership, onUnshareRecord, onUnsharePhoto, onDeletePhoto }: { teamName: string; members: TeamMember[]; records: SharedRecord[]; photos: GrowthPhoto[]; photosLoading: boolean; invitations: TeamInvitation[]; currentUserId: string; currentRole: TeamRole; saving: boolean; error: string | null; invitationSaving: boolean; invitationError: string | null; onBack: () => void; onRoleChange: (id: string, role: "Admin" | "Member") => Promise<boolean>; onCreateInvitation: (email: string) => Promise<boolean>; onRevokeInvitation: (id: string) => Promise<boolean>; onRemoveRecord: (id: string) => void } & TeamManageCallbacks) {
  const canManage = currentRole === "Owner" || currentRole === "Admin"
  const owner = currentRole === "Owner"
  const [inviteEmail, setInviteEmail] = useState("")
  const [selectedPhoto, setSelectedPhoto] = useState<GrowthPhoto | undefined>(); const [confirm, setConfirm] = useState<{ title: string; body: string; run: () => Promise<boolean | void> }>(); const [actionSaving, setActionSaving] = useState(false)
  const ask = (title: string, body: string, run: () => Promise<boolean | void>) => setConfirm({ title, body, run })
  const perform = async () => { if (!confirm) return; setActionSaving(true); try { if (await confirm.run() !== false) setConfirm(undefined) } finally { setActionSaving(false) } }
  return <main style={page}><div style={content}><header style={header}><button onClick={onBack} style={back}>‹</button><div><p style={eyebrow}>TEAM SETTINGS</p><h1 style={title}>{teamName}</h1></div></header><div style={body}>
    <p style={label}>メンバー管理</p><section style={section}>{members.map((member, index) => { const canRemoveMember = member.id !== currentUserId && member.systemRole !== "Owner" && (owner || (currentRole === "Admin" && member.systemRole === "Member")); return <div key={member.id} style={{ ...row, borderBottom: index < members.length - 1 ? "1px solid #282828" : "none" }}><div style={{ flex: 1 }}><p style={name}>{member.name}</p><p style={sub}>システム権限</p></div>{owner && member.id !== currentUserId && member.systemRole !== "Owner" ? <><select disabled={saving || actionSaving} value={member.systemRole} onChange={(event) => void onRoleChange(member.id, event.target.value as "Admin" | "Member")} style={{ ...select, opacity: saving ? .5 : 1 }}><option>Admin</option><option>Member</option></select>{onTransferOwnership && <button disabled={actionSaving} onClick={() => ask("Ownerを移譲しますか？", `${member.name}にOwner権限を移譲します。`, async () => onTransferOwnership(member.id))} style={smallAction}>移譲</button>}</> : <span style={{ ...badge, color: member.systemRole === "Owner" ? "#c8ff00" : "#bbb" }}>{member.systemRole}</span>}{canRemoveMember && onRemoveMember && <button disabled={actionSaving} onClick={() => ask("メンバーを削除しますか？", `${member.name}をチームから削除します。`, async () => onRemoveMember(member.id))} style={remove}>削除</button>}</div> })}{!members.length && <p style={{ padding: 16, color: "#777", fontSize: 13 }}>メンバーが見つかりません</p>}</section>{error && <p role="alert" style={{ color: "#f09a9a", fontSize: 12, lineHeight: 1.5, marginTop: 10 }}>{error}</p>}
    {canManage && <><p style={{ ...label, marginTop: 25 }}>チームへ招待</p><section style={section}><div style={inviteForm}><input type="email" value={inviteEmail} disabled={invitationSaving} onChange={(event) => setInviteEmail(event.target.value)} placeholder="招待するメールアドレス" style={inviteInput} /><button disabled={!inviteEmail.trim() || invitationSaving} onClick={async () => { if (await onCreateInvitation(inviteEmail.trim())) setInviteEmail("") }} style={{ ...inviteButton, opacity: inviteEmail.trim() && !invitationSaving ? 1 : .35 }}>{invitationSaving ? "作成中..." : "招待を作成"}</button></div>{invitationError && <p role="alert" style={inviteError}>{invitationError}</p>}{invitations.map((invitation, index) => <div key={invitation.id} style={{ ...row, borderTop: "1px solid #282828", borderBottom: index < invitations.length - 1 ? "1px solid #282828" : "none" }}><div style={{ flex: 1, minWidth: 0 }}><p style={{ ...name, overflow: "hidden", textOverflow: "ellipsis" }}>{invitation.email}</p><p style={sub}>{new Intl.DateTimeFormat("ja-JP", { month: "numeric", day: "numeric" }).format(new Date(invitation.expiresAt))}まで</p></div><button disabled={invitationSaving} onClick={() => void onRevokeInvitation(invitation.id)} style={{ ...remove, opacity: invitationSaving ? .5 : 1 }}>取消</button></div>)}{!invitations.length && <p style={{ padding: 16, color: "#777", fontSize: 13 }}>招待はありません</p>}</section></>}
    <p style={{ ...label, marginTop: 25 }}>共有トレーニング記録</p><section style={section}>{records.map((record, index) => <div key={record.id} style={{ ...row, borderBottom: index < records.length - 1 ? "1px solid #282828" : "none" }}><div style={{ flex: 1 }}><p style={name}>{record.member}<small style={meta}>{record.when}</small></p><p style={sub}>{record.exercise} · {record.weight ? `${record.weight}kg × ` : ""}{record.reps}回</p></div>{canManage && <button disabled={actionSaving} onClick={() => ask("共有を解除しますか？", "この記録をチームから非表示にします。", async () => onUnshareRecord ? onUnshareRecord(record.id) : onRemoveRecord(record.id))} style={remove}>共有解除</button>}</div>)}{!records.length && <p style={{ padding: 16, color: "#777", fontSize: 13 }}>共有記録はありません</p>}</section>
    <p style={{ ...label, marginTop: 25 }}>共有履歴</p><section style={section}>{photosLoading ? <p style={{ padding: 16, color: "#777", fontSize: 13 }}>読み込み中...</p> : photos.length ? <div style={photoGrid}>{photos.map((photo) => <button key={photo.id} onClick={() => setSelectedPhoto(photo)} style={photoTile}><img src={photo.imageUrl} alt={`${photo.owner}の共有写真`} style={photoImage} /><span style={photoCaption}>{photo.owner}<small style={photoCaptionDate}>{photo.dateLabel}</small></span></button>)}</div> : <p style={{ padding: 16, color: "#777", fontSize: 13 }}>共有写真はありません</p>}</section>
    <p style={note}>Owner: 権限変更・チーム設定。Admin: メンバー・共有記録管理。Member: 自分の記録作成と共有。</p>
  </div>{selectedPhoto && <div style={photoOverlay}><section style={photoDialog}><div style={photoDialogHead}><div><p style={photoDate}>{selectedPhoto.dateLabel}</p><p style={photoOwner}>{selectedPhoto.owner}</p></div><button onClick={() => setSelectedPhoto(undefined)} style={photoClose}>×</button></div><img src={selectedPhoto.imageUrl} alt={`${selectedPhoto.owner}の共有写真`} style={photoPreview} />{selectedPhoto.note && <p style={photoNote}>{selectedPhoto.note}</p>}{selectedPhoto.ownerId === currentUserId && <div style={photoActions}>{onUnsharePhoto && <button disabled={actionSaving} onClick={() => ask("写真の共有を解除しますか？", "写真は削除せず、自分のみの表示へ戻します。", async () => onUnsharePhoto(selectedPhoto.id))} style={remove}>共有解除</button>}{onDeletePhoto && <button disabled={actionSaving} onClick={() => ask("写真を削除しますか？", "Storage画像と写真記録を削除します。この操作は取り消せません。", async () => onDeletePhoto(selectedPhoto.id))} style={remove}>削除</button>}</div>}</section></div>}{confirm && <div style={photoOverlay}><section style={confirmDialog}><p style={confirmTitle}>{confirm.title}</p><p style={confirmBody}>{confirm.body}</p><div style={confirmActions}><button disabled={actionSaving} onClick={() => setConfirm(undefined)} style={cancelButton}>キャンセル</button><button disabled={actionSaving} onClick={() => void perform()} style={confirmButton}>{actionSaving ? "保存中..." : "確認"}</button></div></section></div>}</div></main>
}
const page = { minHeight: "100vh", display: "flex", justifyContent: "center", background: "#000" } as const
const content = { width: "100%", maxWidth: 430, minHeight: "100vh", background: "#0d0d0d" } as const
const header = { display: "flex", alignItems: "center", gap: 14, padding: "24px 20px 18px", borderBottom: "1px solid #1e1e1e" } as const
const back = { width: 38, height: 38, border: "1px solid #2a2a2a", borderRadius: 10, background: "#202020", color: "#ddd", fontSize: 22, cursor: "pointer" } as const
const eyebrow = { color: "#666", fontFamily: "Inter", fontSize: 11, letterSpacing: ".1em", marginBottom: 4 } as const
const title = { fontFamily: "Outfit", fontSize: 21, fontWeight: 700 } as const
const body = { padding: "22px 24px 40px" } as const
const label = { color: "#777", fontSize: 11, fontWeight: 500, letterSpacing: ".1em", marginBottom: 10 } as const
const section = { overflow: "hidden", border: "1px solid #2a2a2a", borderRadius: 14, background: "#171717" } as const
const row = { display: "flex", alignItems: "center", gap: 10, padding: "14px 16px" } as const
const name = { fontFamily: "Outfit", fontSize: 15, fontWeight: 700 } as const
const meta = { marginLeft: 7, color: "#888", fontFamily: "Inter", fontSize: 10, fontWeight: 400 } as const
const sub = { color: "#777", fontSize: 12, marginTop: 4 } as const
const select = { padding: "8px", border: "1px solid #4c5e00", borderRadius: 8, background: "#1b2500", color: "#c8ff00", fontFamily: "Inter", fontSize: 11 } as const
const inviteForm = { display: "flex", gap: 8, padding: 12 } as const
const inviteInput = { flex: 1, minWidth: 0, height: 38, padding: "0 10px", border: "1px solid #333", borderRadius: 8, background: "#202020", color: "#f0f0f0", outline: "none", fontFamily: "Inter", fontSize: 12 } as const
const inviteButton = { flexShrink: 0, padding: "0 10px", border: "none", borderRadius: 8, background: "#c8ff00", color: "#0d0d0d", fontFamily: "Inter", fontSize: 11, fontWeight: 700, cursor: "pointer" } as const
const inviteError = { padding: "0 12px 12px", color: "#f09a9a", fontSize: 12, lineHeight: 1.5 } as const
const badge = { padding: "5px 7px", border: "1px solid #333", borderRadius: 6, background: "#202020", fontFamily: "Inter", fontSize: 10 } as const
const remove = { border: "none", background: "transparent", color: "#e17b7b", fontFamily: "Inter", fontSize: 11, cursor: "pointer" } as const
const note = { color: "#666", fontSize: 11, lineHeight: 1.6, marginTop: 14 } as const
const photoGrid = { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 8, padding: 12 } as const
const photoTile = { overflow: "hidden", padding: 0, border: "1px solid #333", borderRadius: 9, background: "#202020", color: "#aaa", textAlign: "left", cursor: "pointer" } as const
const photoImage = { display: "block", width: "100%", aspectRatio: "3 / 4", objectFit: "cover", background: "#202020" } as const
const photoCaption = { display: "block", padding: "6px 7px", fontFamily: "Inter", fontSize: 10, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" } as const
const photoCaptionDate = { display: "block", marginTop: 2, color: "#777", fontSize: 9 } as const
const photoOverlay = { position: "fixed", inset: 0, zIndex: 30, display: "flex", alignItems: "center", justifyContent: "center", padding: 24, background: "rgba(0,0,0,.72)" } as const
const photoDialog = { width: "100%", maxWidth: 360, maxHeight: "90vh", overflowY: "auto", padding: 18, border: "1px solid #333", borderRadius: 14, background: "#171717" } as const
const photoDialogHead = { display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 12 } as const
const photoDate = { color: "#c8ff00", fontFamily: "Outfit", fontSize: 16, fontWeight: 700 } as const
const photoOwner = { marginTop: 3, color: "#aaa", fontSize: 12 } as const
const photoClose = { border: "none", background: "transparent", color: "#aaa", fontSize: 20, cursor: "pointer" } as const
const photoPreview = { display: "block", width: "100%", maxHeight: "65vh", objectFit: "contain", background: "#0d0d0d" } as const
const photoNote = { marginTop: 12, color: "#bbb", fontSize: 13, lineHeight: 1.5 } as const
const smallAction = { border: "none", background: "transparent", color: "#c8ff00", fontSize: 10, cursor: "pointer" } as const
const photoActions = { display: "flex", justifyContent: "flex-end", gap: 12, marginTop: 12 } as const
const confirmDialog = { width: "100%", maxWidth: 360, padding: 20, border: "1px solid #333", borderRadius: 14, background: "#171717" } as const
const confirmTitle = { fontFamily: "Outfit", fontSize: 17, fontWeight: 700 } as const
const confirmBody = { marginTop: 8, color: "#aaa", fontSize: 12, lineHeight: 1.5 } as const
const confirmActions = { display: "flex", gap: 8, marginTop: 18 } as const
const cancelButton = { flex: 1, padding: 11, border: "1px solid #333", borderRadius: 8, background: "#202020", color: "#ddd", cursor: "pointer" } as const
const confirmButton = { flex: 1, padding: 11, border: "none", borderRadius: 8, background: "#c8ff00", color: "#0d0d0d", fontWeight: 700, cursor: "pointer" } as const
