import { useState } from "react"

export type TeamRole = "Owner" | "Admin" | "Member"
export type TeamMember = { id: string; name: string; role?: string; systemRole: TeamRole; weeklyCount: number; recent: string }
export type SharedRecord = { id: string; teamId: string; memberId: string; member: string; when: string; exercise: string; reps: number; weight?: number; day?: number; sets?: number }

export default function TeamMemberScreen({ member, records, onBack }: { member: TeamMember; records: SharedRecord[]; onBack: () => void }) {
  const [period, setPeriod] = useState<"week" | "month" | "all">("month")
  const [day, setDay] = useState<number | undefined>()
  const mine = records.filter((record) => record.memberId === member.id)
  const visible = mine.filter((record) => period === "all" || period === "month" || (record.day ?? 0) >= 5)
  const activeDays = new Set(mine.map((record) => record.day))
  return <main style={page}><div style={content}><header style={header}><button onClick={onBack} style={back}>‹</button><div><p style={eyebrow}>TEAM MEMBER</p><h1 style={title}>{member.name}{member.role && <small style={role}>{member.role}</small>}</h1></div></header><div style={body}>
    <div style={{ display: "flex", gap: 24, marginBottom: 23 }}><Metric label="今週" value={member.weeklyCount} /><Metric label="今月" value={mine.length} /></div>
    <p style={label}>8月の実施状況</p><section style={{ ...section, padding: "16px 16px 12px" }}><Calendar days={activeDays} onDay={setDay} /></section>
    <div style={{ display: "flex", gap: 7, margin: "22px 0 12px" }}>{([ ["week", "今週"], ["month", "今月"], ["all", "すべて"] ] as const).map(([value, name]) => <button key={value} onClick={() => setPeriod(value)} style={{ ...chip, borderColor: period === value ? "#c8ff00" : "#333", background: period === value ? "#1b2500" : "#202020", color: period === value ? "#c8ff00" : "#aaa" }}>{name}</button>)}</div>
    <p style={label}>共有履歴</p><section style={section}>{visible.map((record, index) => <div key={record.id} style={{ ...row, borderBottom: index < visible.length - 1 ? "1px solid #282828" : "none" }}><p style={sub}>{record.when}</p><p style={recordName}>{record.exercise} · {record.weight ? `${record.weight}kg × ` : ""}{record.reps}回</p><p style={sub}>{record.sets ?? 1}セット</p></div>)}{!visible.length && <p style={{ padding: 16, color: "#777", fontSize: 13 }}>共有された記録はありません</p>}</section>
  </div>{day && <DayDialog day={day} records={mine.filter((record) => record.day === day)} onClose={() => setDay(undefined)} />}</div></main>
}
function Metric({ label, value }: { label: string; value: number }) { return <div><p style={sub}>{label}</p><p style={{ fontFamily: "Outfit", fontSize: 22, fontWeight: 700, marginTop: 3 }}>{value}<small style={{ color: "#777", fontSize: 12, marginLeft: 3 }}>回</small></p></div> }
function Calendar({ days, onDay }: { days: Set<number | undefined>; onDay: (day: number) => void }) { const first = new Date(2026, 7, 1).getDay(); const cells: (number | null)[] = [...Array(first).fill(null), ...Array.from({ length: 31 }, (_, i) => i + 1)]; return <><div style={week}>{["日", "月", "火", "水", "木", "金", "土"].map((name) => <span key={name}>{name}</span>)}</div><div style={calendar}>{cells.map((value, index) => { if (!value) return <span key={`empty${index}`} />; const active = days.has(value); return <button key={value} disabled={!active} onClick={() => onDay(value)} style={{ ...dayCell, color: value === 9 ? "#c8ff00" : "#888", cursor: active ? "pointer" : "default" }}><span>{value}</span><i style={{ ...dot, background: active ? "#c8ff00" : "transparent" }} /></button> })}</div></> }
function DayDialog({ day, records, onClose }: { day: number; records: SharedRecord[]; onClose: () => void }) { return <div style={overlay}><section style={dialog}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 12 }}><h2 style={dialogTitle}>8月{day}日</h2><button onClick={onClose} style={close}>×</button></div>{records.map((record) => <div key={record.id} style={{ padding: "12px 0", borderTop: "1px solid #282828" }}><p style={recordName}>{record.exercise} · {record.weight ? `${record.weight}kg × ` : ""}{record.reps}回</p><p style={sub}>{record.sets ?? 1}セット</p></div>)}</section></div> }
const page = { minHeight: "100vh", display: "flex", justifyContent: "center", background: "#000" } as const; const content = { width: "100%", maxWidth: 430, minHeight: "100vh", position: "relative", background: "#0d0d0d" } as const; const header = { display: "flex", alignItems: "center", gap: 14, padding: "24px 20px 18px", borderBottom: "1px solid #1e1e1e" } as const; const back = { width: 38, height: 38, border: "1px solid #2a2a2a", borderRadius: 10, background: "#202020", color: "#ddd", cursor: "pointer", fontSize: 22 } as const; const eyebrow = { color: "#666", fontFamily: "Inter", fontSize: 11, letterSpacing: ".1em", marginBottom: 5 } as const; const title = { fontFamily: "Outfit", fontSize: 21, fontWeight: 700 } as const; const role = { marginLeft: 7, color: "#888", fontFamily: "Inter", fontWeight: 400, fontSize: 10 } as const; const body = { padding: "22px 24px 36px" } as const; const label = { color: "#777", fontSize: 11, fontWeight: 500, letterSpacing: ".1em", marginBottom: 10 } as const; const section = { overflow: "hidden", border: "1px solid #2a2a2a", borderRadius: 14, background: "#171717" } as const; const sub = { color: "#777", fontSize: 12, marginTop: 4 } as const; const row = { padding: "14px 16px" } as const; const recordName = { fontFamily: "Outfit", fontSize: 15, fontWeight: 700, marginTop: 6 } as const; const chip = { padding: "7px 11px", border: "1px solid", borderRadius: 15, fontFamily: "Inter", fontSize: 11, cursor: "pointer" } as const; const week = { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", marginBottom: 6, textAlign: "center", color: "#666", fontSize: 10 } as const; const calendar = { display: "grid", gridTemplateColumns: "repeat(7, 1fr)" } as const; const dayCell = { display: "flex", minHeight: 32, flexDirection: "column", alignItems: "center", gap: 3, padding: "3px 0", border: "none", background: "transparent", fontFamily: "Outfit", fontSize: 12 } as const; const dot = { width: 5, height: 5, borderRadius: "50%" } as const; const overlay = { position: "fixed", inset: 0, zIndex: 30, display: "flex", alignItems: "center", justifyContent: "center", padding: 24, background: "rgba(0,0,0,.7)" } as const; const dialog = { width: "100%", maxWidth: 360, padding: 20, border: "1px solid #333", borderRadius: 16, background: "#171717" } as const; const dialogTitle = { fontFamily: "Outfit", fontSize: 18, fontWeight: 700 } as const; const close = { border: "none", background: "transparent", color: "#aaa", fontSize: 20, cursor: "pointer" } as const
