import { useState } from "react"
import type { Workspace } from "./workspace"
export default function WorkspaceManagerScreen({ workspaces, currentId, onBack, onSelect, onRename, onExit, onCreateTeam, onManageTeam }: { workspaces: Workspace[]; currentId: Workspace["id"]; onBack: () => void; onSelect: (id: Workspace["id"]) => void; onRename: (id: Workspace["id"], name: string) => void; onExit: (id: string) => void; onCreateTeam: () => void; onManageTeam: (id: string) => void }) { const [editing, setEditing] = useState<Workspace | undefined>(); const [name, setName] = useState(""); return <main style={pageStyle}><div style={contentStyle}><header style={headerStyle}><button onClick={onBack} style={backStyle}>‹</button><div><p style={eyebrowStyle}>WORKSPACES</p><h1 style={titleStyle}>ワークスペース管理</h1></div></header><div style={{ padding: "22px 24px" }}>{workspaces.map((workspace) => <section key={workspace.id} style={cardStyle}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ flex: 1 }}><p style={{ fontFamily: "Outfit", fontSize: 16, fontWeight: 700 }}>{workspace.name}{workspace.id === currentId && <small style={activeStyle}>使用中</small>}</p><p style={{ color: "#777", fontSize: 12, marginTop: 5 }}>{workspace.type}{workspace.type === "チーム" ? ` · ${workspace.systemRole}` : ""}</p></div><button onClick={() => { setEditing(workspace); setName(workspace.name) }} style={editStyle}>名前変更</button></div>{workspace.type === "チーム" && <div style={{ marginTop: 14, paddingTop: 13, borderTop: "1px solid #282828" }}><button onClick={() => onManageTeam(workspace.id)} style={{ ...editStyle, marginRight: 14 }}>メンバー・共有記録を管理</button><button onClick={() => onExit(workspace.id)} style={exitStyle}>チームを退出</button></div>}<button onClick={() => onSelect(workspace.id)} style={selectStyle}>{workspace.id === currentId ? "現在選択中" : "このワークスペースへ切替"}</button></section>)}<button onClick={onCreateTeam} style={createStyle}>＋ チームを作成</button></div>{editing && <div style={overlayStyle}><section style={dialogStyle}><p style={{ fontFamily: "Outfit", fontSize: 17, fontWeight: 700, marginBottom: 12 }}>ワークスペース名</p><input value={name} onChange={(event) => setName(event.target.value)} style={inputStyle} /><div style={{ display: "flex", gap: 8, marginTop: 16 }}><button onClick={() => setEditing(undefined)} style={cancelStyle}>キャンセル</button><button onClick={() => { if (name.trim()) onRename(editing.id, name.trim()); setEditing(undefined) }} style={saveStyle}>保存</button></div></section></div>}</div></main> }
const pageStyle = { minHeight: "100vh", display: "flex", justifyContent: "center", background: "#000" } as const
const contentStyle = { width: "100%", maxWidth: 430, minHeight: "100vh", background: "#0d0d0d" } as const
const headerStyle = { display: "flex", alignItems: "center", gap: 14, padding: "24px 20px 18px", borderBottom: "1px solid #1e1e1e" } as const
const backStyle = { width: 38, height: 38, border: "1px solid #2a2a2a", borderRadius: 10, background: "#202020", color: "#ddd", cursor: "pointer", fontSize: 22 } as const
const eyebrowStyle = { color: "#666", fontFamily: "Inter", fontSize: 11, letterSpacing: "0.1em", marginBottom: 4 } as const
const titleStyle = { fontFamily: "Outfit", fontSize: 21, fontWeight: 700 } as const
const cardStyle = { padding: 16, marginBottom: 10, border: "1px solid #2a2a2a", borderRadius: 14, background: "#171717" } as const
const activeStyle = { marginLeft: 7, color: "#c8ff00", fontFamily: "Inter", fontWeight: 400, fontSize: 10 } as const
const editStyle = { padding: "8px 9px", border: "1px solid #333", borderRadius: 8, background: "transparent", color: "#c8ff00", fontSize: 11, cursor: "pointer" } as const
const exitStyle = { padding: 0, border: "none", background: "transparent", color: "#d77", fontSize: 12, cursor: "pointer" } as const
const selectStyle = { width: "100%", marginTop: 14, padding: "10px", border: "1px solid #333", borderRadius: 9, background: "#202020", color: "#bbb", fontFamily: "Inter", fontSize: 12, cursor: "pointer" } as const
const createStyle = { width: "100%", padding: 15, border: "1px dashed #4a4a4a", borderRadius: 12, background: "transparent", color: "#c8ff00", fontFamily: "Inter", fontSize: 13, cursor: "pointer" } as const
const overlayStyle = { position: "fixed", inset: 0, zIndex: 30, display: "flex", alignItems: "center", justifyContent: "center", padding: 24, background: "rgba(0,0,0,.7)" } as const
const dialogStyle = { width: "100%", maxWidth: 360, padding: 20, border: "1px solid #333", borderRadius: 16, background: "#171717" } as const
const inputStyle = { width: "100%", height: 48, padding: "0 12px", border: "1px solid #333", borderRadius: 9, background: "#202020", color: "#f0f0f0", outline: "none" } as const
const cancelStyle = { flex: 1, height: 44, border: "1px solid #333", borderRadius: 9, background: "#202020", color: "#ddd", cursor: "pointer" } as const
const saveStyle = { flex: 1, height: 44, border: "none", borderRadius: 9, background: "#c8ff00", color: "#0d0d0d", fontWeight: 700, cursor: "pointer" } as const
